### ISSUE TITLE
Incompatibilty with Orebfuscator

### ISSUE THREAD

**Issue by stonegray** [Cavallium/CoordinatesObfuscator#5]
When Orebfuscator is also installed, CoordinatesObfuscator throws an error on player login. Not sure if this is related to CoordinatesObfuscator or Orebufscator, but figured I'd document the error here.

- CoordinatesObfuscator 1.3.6 from Spigot 
- Tuinity 1.16.4 (https://github.com/Spottedleaf/Tuinity/commit/8954b61610c3f0371e9ae388c0a95569b074095c)
- Orebfuscator 5.1.3 (https://github.com/Imprex-Development/Orebfuscator/commit/4d1d4b38ab5b0d6f58c5e000ad4c686a8072d514)

<details>
<summary>
<b>Stack trace</b> (click to expand)
</summary>

```text
[15:20:48 ERROR]: [CoordinatesObfuscator] Unhandled exception occured in onPacketSending(PacketEvent) for CoordinatesObfuscator
com.comphenix.protocol.reflect.FieldAccessException: Cannot get NBT type of net.minecraft.server.v1_16_R3.PacketPlayOutTileEntityData@75cfa3ad
        at com.comphenix.protocol.wrappers.nbt.WrappedElement.getType(WrappedElement.java:150) ~[?:?]
        at com.comphenix.protocol.wrappers.nbt.NbtFactory.fromNMS(NbtFactory.java:334) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:634) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:42) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$2.getSpecific(BukkitConverters.java:276) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$2.getSpecific(BukkitConverters.java:268) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:42) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.getValues(StructureModifier.java:678) ~[?:?]
        at org.warp.coordinatesobfuscator.CoordinatesObfuscator.cloneMapChunkEntitiesData(CoordinatesObfuscator.java:201) ~[?:?]
        at org.warp.coordinatesobfuscator.CoordinatesObfuscator.access$100(CoordinatesObfuscator.java:33) ~[?:?]
        at org.warp.coordinatesobfuscator.CoordinatesObfuscator$1.onPacketSending(CoordinatesObfuscator.java:115) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:466) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.NetworkManager.processQueue(NetworkManager.java:513) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.NetworkManager.p(NetworkManager.java:479) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacketQueue(NetworkManager.java:473) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:335) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1739) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1712) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1942) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.a(PlayerChunkMap.java:2308) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.sendChunk(PlayerChunkMap.java:2242) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.Chunk.lambda$onNeighbourChange$1(Chunk.java:388) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1210) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1224) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:677) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.IChunkProvider.getChunkAt(SourceFile:16) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.imprex.orebfuscator.nms.v1_16_R3.NmsManager.getBlockData(NmsManager.java:52) ~[?:?]
        at net.imprex.orebfuscator.nms.v1_16_R3.NmsManager.loadChunkAndGetBlockId(NmsManager.java:135) ~[?:?]
        at net.imprex.orebfuscator.NmsInstance.loadChunkAndGetBlockId(NmsInstance.java:86) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.areAjacentBlocksTransparent(Obfuscator.java:145) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.areAjacentBlocksTransparent(Obfuscator.java:156) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.shouldObfuscate(Obfuscator.java:133) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.obfuscateNow(Obfuscator.java:86) ~[?:?]
        at net.imprex.orebfuscator.obfuscation.Obfuscator.lambda$obfuscate$0(Obfuscator.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@454197d
        at jdk.internal.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.comphenix.protocol.wrappers.nbt.WrappedElement.getType(WrappedElement.java:148) ~[?:?]
        ... 60 more
```
</details>

<details>
<summary>
<b>Error Parameters</b> (click to expand)
</summary>

```text
[15:20:48 ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutMapChunk@14d7b756[
    a=68
    b=1
    c=31
    d={MOTION_BLOCKING:[L;1281525272952211526L,1317659898773541957L,1263475208901399105L,1335709412800105543L,1155318724919597132L,1335322109427093062L,1155600749920557130L,1263546127938519104L,1389823183500378176L,1299539602071126092L,1371773392847408199L,1155177711076939853L,1353336438277046342L,1155178468601796683L,1263440023991124032L,1155530312188466763L,1155177711073787968L,1353759133390375488L,1155177711073787968L,1371738277194793024L,1173227293955364427L,1155177779927745089L,1155177711076677195L,1173262616035361857L,1155177711073787968L,1209326666145628224L,1155177711073788482L,1209326528437977152L,1155177711208531524L,1173192109583269952L,1155213033287747138L,1155177711073787968L,1191277014544843328L,1155177711073787969L,1173227362809053248L,1155177711074050625L,8606744640L],WORLD_SURFACE:[L;1281525272952211526L,1317659898773541957L,1263475208901399105L,1335709412800105543L,1155318724919597132L,1335322109427093062L,1155600749920557130L,1263546127938519104L,1389823183500378176L,1299539602071126092L,1371773392847408199L,1155177711076939853L,1353336438277046342L,1155178468601796683L,1263440023991124032L,1173544710697948747L,1155177711073787968L,1353759133390375488L,1155177711073788481L,1371738277194793024L,1173227294089844299L,1155177779927745089L,1155212964302460491L,1173262616035361857L,1173227362809053248L,1209326666145628224L,1173227293955359298L,1209326528438239809L,1155177711208531524L,1173192178437227073L,1155213033287747138L,1173227362809315392L,1191277014544843328L,1173227293955620929L,1173227362809053249L,1155177711074050625L,8606744640L]}
    e={4, ... ,4}
    f= [removed]
    h=true
    ready=true
    extraPackets=[net.minecraft.server.v1_16_R3.PacketPlayOutTileEntityData@75cfa3ad, net.minecraft.server.v1_16_R3.PacketPlayOutTileEntityData@34f9dcaf, net.minecraft.server.v1_16_R3.PacketPlayOutTileEntityData@7f5cb789, net.minecraft.server.v1_16_R3.PacketPlayOutTileEntityData@539edd41, net.minecraft.server.v1_16_R3.PacketPlayOutTileEntityData@e7b67]
    mustSplit=false
  ]
```
</details>
<details>
<summary>
<b>Hang thread dump</b> (click to expand)
</summary>

```text
[15:21:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Tuinity-"8954b61" (MC: 1.16.4) ---
[15:21:28 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[15:21:28 ERROR]: ------------------------------
[15:21:28 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[15:21:28 ERROR]: Chunk wait task info below: 
[15:21:28 ERROR]: -36538,-4240 in 'survival:
[15:21:28 ERROR]: Load Task - none
[15:21:28 ERROR]: Save Task - none
[15:21:28 ERROR]: Chunk Holder - non-null
[15:21:28 ERROR]: Chunk Status - minecraft:features
[15:21:28 ERROR]: Chunk Ticket Status - minecraft:full
[15:21:28 ERROR]: Chunk Holder Status - minecraft:features
[15:21:28 ERROR]: Chunk Holder Priority - 2
[15:21:28 ERROR]: Chunk Neighbors: 
[15:21:28 ERROR]:   -36537,-4239 in survival:
[15:21:28 ERROR]:   Chunk Holder - non-null
[15:21:28 ERROR]:   Chunk Status - minecraft:liquid_carvers
[15:21:28 ERROR]:   Chunk Ticket Status - minecraft:features
[15:21:28 ERROR]:   Chunk Holder Status - minecraft:liquid_carvers
[15:21:28 ERROR]:   Chunk Holder Priority - 3
[15:21:28 ERROR]:   Chunk Neighbors: 
[15:21:28 ERROR]:     -36536,-4238 in survival:
[15:21:28 ERROR]:     Chunk Holder - non-null
[15:21:28 ERROR]:     Chunk Status - minecraft:surface
[15:21:28 ERROR]:     Chunk Ticket Status - minecraft:liquid_carvers
[15:21:28 ERROR]:     Chunk Holder Status - minecraft:surface
[15:21:28 ERROR]:     Chunk Holder Priority - 35
[15:21:28 ERROR]: ------------------------------
[15:21:28 ERROR]: Current Thread: Server thread
[15:21:28 ERROR]:       PID: 16 | Suspended: false | Native: false | State: TIMED_WAITING
[15:21:28 ERROR]:       Stack:
[15:21:28 ERROR]:               java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
[15:21:28 ERROR]:               java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.bm(IAsyncTaskHandler.java:131)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:677)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.IChunkProvider.getChunkAt(SourceFile:16)
[15:21:28 ERROR]:               net.imprex.orebfuscator.nms.v1_16_R3.NmsManager.getBlockData(NmsManager.java:52)
[15:21:28 ERROR]:               net.imprex.orebfuscator.nms.v1_16_R3.NmsManager.loadChunkAndGetBlockId(NmsManager.java:135)
[15:21:28 ERROR]:               net.imprex.orebfuscator.NmsInstance.loadChunkAndGetBlockId(NmsInstance.java:86)
[15:21:28 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.areAjacentBlocksTransparent(Obfuscator.java:145)
[15:21:28 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.areAjacentBlocksTransparent(Obfuscator.java:155)
[15:21:28 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.shouldObfuscate(Obfuscator.java:133)
[15:21:28 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.obfuscateNow(Obfuscator.java:86)
[15:21:28 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.lambda$obfuscate$0(Obfuscator.java:39)
[15:21:28 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator$$Lambda$7158/0x0000000801eb9c40.run(Unknown Source)
[15:21:28 ERROR]:               app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[15:21:28 ERROR]:               app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1264)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[15:21:28 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3123/0x00000008008fec40.run(Unknown Source)
[15:21:28 ERROR]:               java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)
[15:21:28 ERROR]: ------------------------------
[15:21:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[15:21:28 ERROR]: ------------------------------
[15:21:33 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Tuinity-"8954b61" (MC: 1.16.4) ---
[15:21:33 ERROR]: The server has not responded for 15 seconds! Creating thread dump
[15:21:33 ERROR]: ------------------------------
[15:21:33 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[15:21:33 ERROR]: Chunk wait task info below: 
[15:21:33 ERROR]: -36530,-4242 in 'survival:
[15:21:33 ERROR]: Load Task - none
[15:21:33 ERROR]: Save Task - none
[15:21:33 ERROR]: Chunk Holder - non-null
[15:21:33 ERROR]: Chunk Status - minecraft:light
[15:21:33 ERROR]: Chunk Ticket Status - minecraft:full
[15:21:33 ERROR]: Chunk Holder Status - minecraft:features
[15:21:33 ERROR]: Chunk Holder Priority - 2
[15:21:33 ERROR]: ------------------------------
[15:21:33 ERROR]: Current Thread: Server thread
[15:21:33 ERROR]:       PID: 16 | Suspended: false | Native: false | State: TIMED_WAITING
[15:21:33 ERROR]:       Stack:
[15:21:33 ERROR]:               java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
[15:21:33 ERROR]:               java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.bm(IAsyncTaskHandler.java:131)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:677)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.IChunkProvider.getChunkAt(SourceFile:16)
[15:21:33 ERROR]:               net.imprex.orebfuscator.nms.v1_16_R3.NmsManager.getBlockData(NmsManager.java:52)
[15:21:33 ERROR]:               net.imprex.orebfuscator.nms.v1_16_R3.NmsManager.loadChunkAndGetBlockId(NmsManager.java:135)
[15:21:33 ERROR]:               net.imprex.orebfuscator.NmsInstance.loadChunkAndGetBlockId(NmsInstance.java:86)
[15:21:33 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.areAjacentBlocksTransparent(Obfuscator.java:145)
[15:21:33 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.areAjacentBlocksTransparent(Obfuscator.java:155)
[15:21:33 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.shouldObfuscate(Obfuscator.java:133)
[15:21:33 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.obfuscateNow(Obfuscator.java:86)
[15:21:33 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator.lambda$obfuscate$0(Obfuscator.java:39)
[15:21:33 ERROR]:               net.imprex.orebfuscator.obfuscation.Obfuscator$$Lambda$7158/0x0000000801eb9c40.run(Unknown Source)
[15:21:33 ERROR]:               app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[15:21:33 ERROR]:               app//org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1264)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[15:21:33 ERROR]:               app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3123/0x00000008008fec40.run(Unknown Source)
[15:21:33 ERROR]:               java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)
[15:21:33 ERROR]: ------------------------------
[15:21:33 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[15:21:33 ERROR]: ------------------------------
```
</details>

**Comment by Cavallium** [comment]
This seems a problem related to protocollib
