### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by axilirate** [Cavallium/CoordinatesObfuscator#6]
```
[12:16:33 ERROR]: [CoordinatesObfuscator] Unhandled exception number 131072 occured in onPacketSending(PacketEvent) for CoordinatesObfuscator
java.lang.NoClassDefFoundError: Could not initialize class org.warp.coordinatesobfuscator.TranslatorClientbound
        at org.warp.coordinatesobfuscator.CoordinatesObfuscator$1.onPacketSending(CoordinatesObfuscator.java:121) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:421) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2050) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2036) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:2299) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:207) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2023) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2034) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1071) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:932) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:817) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1626) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-AirplanePurpur-"e9bf399"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Cavallium** [comment]
I'm working on 1.17 support, but keep in mind that I'm quite busy currently, don't expect it to be released this month

**Comment by Cavallium** [comment]
Fixed
