### ISSUE TITLE
Update for 1.18

### ISSUE THREAD

**Issue by UmpquaRiver** [cavallium/CoordinatesObfuscator#9]
I've tried running this plugin on the latest Java release, 1.18, and got this error in console.

> [CoordinatesObfuscator] Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for CoordinatesObfuscator
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Collection exists in class ClientboundLevelChunkWithLightPacket.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.modify(StructureModifier.java:423) ~[?:?]
	at org.warp.coordinatesobfuscator.TranslatorClientbound.sendChunk(TranslatorClientbound.java:296) ~[?:?]
	at org.warp.coordinatesobfuscator.TranslatorClientbound.outgoing(TranslatorClientbound.java:140) ~[?:?]
	at org.warp.coordinatesobfuscator.CoordinatesObfuscator$1.onPacketSending(CoordinatesObfuscator.java:134) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:183) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1701) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1687) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1938) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1365) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:944) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1114) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:1262) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.ChunkProviderServer.b(ChunkProviderServer.java:558) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.WorldServer$a.e(WorldServer.java:1857) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:1) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.e(PersistentEntitySectionManager.java:146) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.a(PersistentEntitySectionManager.java:109) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.a(PersistentEntitySectionManager.java:90) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.WorldServer.e(WorldServer.java:980) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.level.WorldServer.c(WorldServer.java:964) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.players.PlayerList.a(PlayerList.java:315) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.network.LoginListener.a(LoginListener.java:193) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.network.LoginListener.b(LoginListener.java:74) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at java.lang.Thread.run(Thread.java:833) [?:?]

A big thank you for developing this plugin. It's incredibly maddening to see people review bomb the plugin page because it wasn't updated within _hours_ of the game's new version release.

**Comment by cavallium** [comment]
Unfortunately I can't start working on the next version until Protocollib releases a fully compatible version for Minecraft 1.18.


<i>I just noticed the one star review, lol</i>

**Comment by Ashesh3** [comment]
@cavallium hey! is it possible now? with the dev builds? They are pretty stable!

**Comment by cavallium** [comment]
Hi, sorry but I can't continue the project, I don't have enough free time.
The project is quite simple to upgrade to 1.18 by the way, I hope that someone will open a pull request with the updated code.
